### ISSUE TITLE
[Bug]: 【Player API】.setTitle 遇到添加副标题[subtitle] 自动回到原版默认的淡入、持续和淡出时间

### ISSUE THREAD

**Issue by superwfox** [LiteLDev/LegacyScriptEngine#106]
### Describe the bug

【Player API】.setTitle 遇到添加副标题[subtitle]自动回到原版默认的淡入、持续和淡出时间

### To Reproduce

`//这边为玩家设置一个主标题【title】
 pl.setTitle('§空', 2, 0, 12000, 0) //持续12000tick

//再添加一个副标题【subtitlt】
player.setTitle(`${s_title_up}`, 3, 0, 12000, 0)//持续12000tick

//最后整个标题只停留70tick
`

### Expected behavior

应该和 主标题 持续时间 保持一致

### Screenshots

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/65709399/d56e2476-1a25-4d78-8cf0-da6e969028a5)

### Platform

windows 10

### BDS Version

1.20.72

### LeviLamina Version

LeviLamina-0.10.2+c5acae6cb

**Comment by ShrBox** [comment]
一般不是先subtitle再title吗

**Comment by ShrBox** [comment]
无法复现

**Comment by superwfox** [comment]
我是0.5.2升级一下
