### ISSUE TITLE
[Bug]: mc.runcmd("backup") 报错 unknown operation （概率性？）

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#113]
### Describe the bug

mc.runcmd("backup") 报错 unknown operation

以下是js代码：
（整点执行备份指令）
![99360ec479db0e8e9f5a274d58c84301](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/7233f688-a87a-414f-bd26-c623a6ed1f4c)

在LL0.11.1 LSE0.6.4中正常使用，目前不清楚是backuphelper插件的问题还是LSE的问题

### To Reproduce

装backuphelper插件
使用mc.runcmd("backup")

### Expected behavior

正常使用mc.runcmd("backup")

### Screenshots

![99360ec479db0e8e9f5a274d58c84301](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/b45eea01-7f21-41f1-a9a9-e5b71f0c351d)

### Platform

win10

### BDS Version

1.20.80

### LeviLamina Version

0.12.1

### LegacyScriptEngine Version

0.7.2

**Comment by yufengya0420** [comment]
![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/76a41682-eb77-466a-814e-fd30a1978347)

从图中可以看到，有的整点成功备份了，而有的整点并没有备份，所以是概率性出现这个问题

**Comment by yufengya0420** [comment]
![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/4ce42e57-4aa2-44b8-a039-e06dbd20b7c2)

**Comment by yufengya0420** [comment]
> ![image](https://private-user-images.githubusercontent.com/99462074/326827538-4ce42e57-4aa2-44b8-a039-e06dbd20b7c2.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ0ODQyODYsIm5iZiI6MTcxNDQ4Mzk4NiwicGF0aCI6Ii85OTQ2MjA3NC8zMjY4Mjc1MzgtNGNlNDJlNTctNGFhMi00NGI4LWEwMzktZTA2ZGJkMjBiN2MyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDMwVDEzMzMwNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWE4OWNiOTU2MDVkNzg4ODI3Y2Q2MmY0YjUwODJhNWRlMzUwMmJiOGM3OWZhYTI2NDU2NjVkODUyYmI2NjljNDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.v5p8kaZDRiKlrUjLl4NDMIgJDcM5icZstEF-5vSTqJg)

好像是所有控制台指令都有问题

**Comment by ShrBox** [comment]
"unknown operation"是BackupHelper的输出，虽然不知道什么原因导致的[BackupOperation](https://github.com/ShrBox/BackupHelper/blob/e00d8a1c85202a9d8832303d94a5c9be7ebf5ff0/src/OldBackupHelper/BackupCommand.cpp#L100)不为<=0<=3，但我认为这段hape判断代码也有问题，请尝试将BackupHelper升级至0.4.2
