### ISSUE TITLE
mc.getStructure 获取结构nbt API 貌似又无法正常使用了

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#114]
Solved in https://github.com/LiteLDev/LeviLamina/commit/45c903a826897bc229208d3dac067ff1aad15c30

_Originally posted by @ShrBox in https://github.com/LiteLDev/LegacyScriptEngine/issues/97#issuecomment-2049827260_

**Comment by yufengya0420** [comment]
并且CALL的选区操作功能直接会导致崩服，但是这在BDS1.20.73中可以正常使用，在BDS1.20.80中无法正常使用

**Comment by yufengya0420** [comment]
https://github.com/LiteLDev/LegacyScriptEngine/issues/97#issuecomment-2049827260

**Comment by ShrBox** [comment]
https://github.com/LiteLDev/LeviLamina/commit/9fbd6de71458b9e15a83c6fe239f2b19698a574c
