### ISSUE TITLE
[Bug]: 获取玩家主世界的出生点坐标会崩服玩家 player.teleport（Player.getRespawnPosition（））

### ISSUE THREAD

**Issue by WuHuiZhang6902** [LiteLDev/LegacyScriptEngine#115]
### Describe the bug

获取玩家主世界的出生点坐标会崩服

### To Reproduce

Player.teleport(Player.getRespawnPosition())

### Expected behavior

修复该问题

### Platform

Windows 10

### BDS Version

1.20.72

### LeviLamina Version

0.11.0

### LegacyScriptEngine Version

0.6.4

**Comment by ShrBox** [comment]
鉴定为玩家没有设置重生点时Mojang的API会返回一串神必负数做为坐标和维度，调用API传送到此坐标自然会导致崩溃
