### ISSUE TITLE
[Bug]: ct.getItem() API 无法正常工作

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#116]
### Describe the bug

![239bc1cd9f635c5782c77b15dda4ac72](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/4b821484-2212-4827-b449-abee9eb48fdf)

ct.getItem() API 无法正常工作

### To Reproduce

使用 ct.getItem() API

### Expected behavior

正常工作

### Screenshots

![239bc1cd9f635c5782c77b15dda4ac72](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/ae065033-ec79-48cd-ae22-f315b3973744)

### Platform

Win10

### BDS Version

1.20.81

### LeviLamina Version

0.12.2

### LegacyScriptEngine Version

0.7.3

**Comment by yufengya0420** [comment]
![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/8c93174a-46df-47fb-9bcc-398d6543dc9b)

**Comment by ShrBox** [comment]
![图片](https://github.com/LiteLDev/LegacyScriptEngine/assets/53301243/74f04a38-a3fe-4870-965e-bf074e07cd56)
无法复现，图中控制台的错误原因是插件传入了错误的参数类型

**Comment by yufengya0420** [comment]
> ![图片](https://private-user-images.githubusercontent.com/53301243/327096750-74f04a38-a3fe-4870-965e-bf074e07cd56.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTQ1ODExNTEsIm5iZiI6MTcxNDU4MDg1MSwicGF0aCI6Ii81MzMwMTI0My8zMjcwOTY3NTAtNzRmMDRhMzgtYTNmZS00ODcwLTk2NWUtYmYwNzRlMDdjZDU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MDElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTAxVDE2MjczMVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZmM5MzZjMGIwYzljZmNjMWVkM2ZjMDhjNzAwNWNhMzExMWNhNDg5Zjg3ZWQzM2ZmZWIzZTlkODcyNzlhNTkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.3FVap0JOEcMJvU_oQYEMQBc2RjwsWns-pDZh4o7rm3I) 无法复现，图中控制台的错误原因是插件传入了错误的参数类型 需要更多信息

call那边说同样的插件在之前是可用的，更新后就报错
