### ISSUE TITLE
[Bug]: Raw Seh Exception:[0xC0000005:ntstatus] 0x%p 指令引用了 0x%p 内存。该内存不能为 %s。 Parameter 0: 0x0  Parameter 1: 0xffffffffffffffff

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#121]
### Describe the bug

![071c57ed9abafb0f447ac2108f3e8a0c](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/cce22e6a-9624-433e-9e2a-e903c31a52d2)

![2390a4ba31d9d98ca91e2defd5366e98](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/69140328-475e-41e1-9436-e81840469b6b)

插件：GMLIB：https://github.com/GroupMountain/GMLIB
GMLIB-GMLIB-LegacyRemoteCallApi：https://github.com/GroupMountain/GMLIB-LegacyRemoteCallApi
LSE 0.7.4 和 LSE 0.7.5 都会报错 ， 但是在 LSE 0.7.3 以及之前的版本中正常，目前不清楚是LSE的问题还是插件的问题
报错持续刷屏已经严重影响到游戏体验了，希望尽快修复

### To Reproduce
给服务器装GMLIB和GMLIB-LRCA
然后加上这个插件：
![2390a4ba31d9d98ca91e2defd5366e98](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/225e7fc9-f781-49db-8d81-c241ac30b765)
![071c57ed9abafb0f447ac2108f3e8a0c](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/22630957-f197-4ee4-89cc-c659d8cf8e8e)

### Expected behavior

像LSE0.7.3版本中那样正常使用，不报错

### Screenshots

![071c57ed9abafb0f447ac2108f3e8a0c](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/efca0473-a893-4704-88a9-09a5e9143a54)

![2390a4ba31d9d98ca91e2defd5366e98](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/30f989de-ca00-4b4f-9a45-c26778f269b5)

### Platform

Win10

### BDS Version

1.20.81

### LeviLamina Version

0.12.2

### LegacyScriptEngine Version

0.7.4

**Comment by ShrBox** [comment]
Fixed in a9cb57f5a709de2c50b4c65e4d22848add9eac22
