### ISSUE TITLE
[Bug]: LSE0.7.6 NBT.parseSNBT(snbt) api失效

### ISSUE THREAD

**Issue by Hurry1027** [LiteLDev/LegacyScriptEngine#122]
### Describe the bug

NBT.parseSNBT(snbt) api失效，解析玩家SNBT返回为null。

### To Reproduce

jsdebug
15:00:43.328 INFO [legacy-script-engine-quickjs] Debug mode begins
NBT.parseSNBT(mc.getOnlinePlayers()[0].getNbt().toSNBT())
15:01:18.157 INFO [legacy-script-engine-quickjs] Null
mc.getOnlinePlayers()[0].getNbt().toSNBT().length
15:01:28.985 INFO [legacy-script-engine-quickjs] 71772

### Expected behavior

修复此问题，谢谢大佬~
返回玩家NBT而不是null

### BDS Version

1.20.81

### LeviLamina Version

0.12.1

### LegacyScriptEngine Version

0.7.6

**Comment by ShrBox** [comment]
![图片](https://github.com/LiteLDev/LegacyScriptEngine/assets/53301243/32adfaf9-abfa-4d6b-a2d9-3c167578a430)
在添加了向控制台输出错误信息后，我得到了"数字超出范围"的错误

**Comment by ShrBox** [comment]
已于 https://github.com/LiteLDev/LeviLamina/commit/c94d1408e6a00a3b93a8371c9abc1d6c5b03c98e 中修复，需要将LeviLamina升级到新版本才能解决此问题，稍后会发新版
