### ISSUE TITLE
[Feature]: 希望nodejs引擎取消migrate时生成manifest.jsom

### ISSUE THREAD

**Issue by xianyubb** [LiteLDev/LegacyScriptEngine#126]
### Is your feature request related to a problem? Please describe.

是这样的,在nodejs开发过程中,在发布整合插件阶段,会整合为llplugin的压缩包,而我认为,开发者可以将manifest.json一起塞在里面.
这样既可以让开发者在manifest.json塞下更多信息.也方便了插件加载.我想,作为插件开发者,熟悉manifest.json是必然的.
其次,我在开发时遇到一个问题,比如我的nodejs插件migrate后,生成的manifest.json的entry一项为空字符串,不知是否为bug
可能是因为我插件文件夹的名字和入口文件名字不符.所以结合以上三点,希望nodejs 引擎取消migrate时生成manifest.jsom

### Describe the solution you'd like

希望nodejs 引擎取消migrate时生成manifest.jsom

**Comment by ShrBox** [comment]
别打包成.llplugin，这是属于LL2的旧格式，请直接使用lip进行分发或打包成.zip让用户手动解压

**Comment by ShrBox** [comment]
我加了个判断，如果manifest.json存在就不覆盖

**Comment by xianyubb** [comment]
好好好,你就是我大爸
