### ISSUE TITLE
[Bug]: getBlock函数获取方块的name和type返回值是一样的

### ISSUE THREAD

**Issue by WuHuiZhang6902** [LiteLDev/LegacyScriptEngine#130]
### Describe the bug

bl.name和bl.type的获取值是一样的

### To Reproduce

mc.getBlock(pos).name

### Expected behavior

像获取物品函数的name一样获取方块name

### Platform

Windows 10

### BDS Version

1.20.80

### LeviLamina Version

0.12.2

### LegacyScriptEngine Version

0.7.1

**Comment by yufengya0420** [comment]
你可以试试lse最新版

**Comment by ShrBox** [comment]
> 你可以试试lse最新版

我瞅了一眼，发现这问题从LLSE时期就开始存在了

**Comment by WuHuiZhang6902** [comment]
> > 你可以试试lse最新版
> 
> 我瞅了一眼，发现这问题从LLSE时期就开始存在了

那这个问题可以修复吗？

**Comment by ShrBox** [comment]
> > > 你可以试试lse最新版
> > 
> > 
> > 我瞅了一眼，发现这问题从LLSE时期就开始存在了
> 
> 那这个问题可以修复吗？

我有时间改下

**Comment by WuHuiZhang6902** [comment]
0.7.9的releases只发了源码，没有发本体

**Comment by yufengya0420** [comment]
> 0.7.9的releases只发了源码，没有发本体

等一会就有了
