### ISSUE TITLE
[Bug]: LSE-nodejs的bug？

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#133]
### Describe the bug

目前不知道什么问题
![ba841a5b3c42f2aae8a0b08e8cafb0f7](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/53eeeb2e-69c3-4179-bf18-335d104dd5e8)

![9b6f9b42d9c773acb67f096ea109bd1d](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/1c7fdba7-45ae-403f-96ba-3f0ffb045248)

### To Reproduce

[sparkbridge2.zip](https://github.com/LiteLDev/LegacyScriptEngine/files/15276362/sparkbridge2.zip)

装上这个插件

### Expected behavior

不报错 不崩服

### Screenshots

![ba841a5b3c42f2aae8a0b08e8cafb0f7](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/53eeeb2e-69c3-4179-bf18-335d104dd5e8)

![9b6f9b42d9c773acb67f096ea109bd1d](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/1c7fdba7-45ae-403f-96ba-3f0ffb045248)

### Platform

Win10

### BDS Version

1.20.81

### LeviLamina Version

0.12.3

### LegacyScriptEngine Version

0.7.10

**Comment by yufengya0420** [comment]
![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/793ea983-d969-4004-88f1-376586a7354b)

**Comment by yufengya0420** [comment]
[crash.zip](https://github.com/LiteLDev/LegacyScriptEngine/files/15276370/crash.zip)

**Comment by ShrBox** [comment]
无法复现，图中报错为json换行符问题
