### ISSUE TITLE
[Bug]: 发包时写入NBT数据函数为null

### ISSUE THREAD

**Issue by zimuya4153** [LiteLDev/LegacyScriptEngine#135]
### Describe the bug

发包时写入NBT数据函数为null

### To Reproduce

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/163636894/259d74e3-654f-43da-a476-a867bcfde4d8)
控制台依次输入
jsdebug
bs = new BinaryStream();
bs.writeCompountTag;

### Expected behavior

修复这个问题

### Screenshots

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/163636894/0a18a8e6-007f-495e-9708-11ce15ac8ffc)

### Platform

Windows 10

### BDS Version

1.20.81-1.671+a9081c5

### LeviLamina Version

LeviLamina-0.12.3+032fa4e52

### LegacyScriptEngine Version

0.7.11

**Comment by ShrBox** [comment]
writeCompoundTag
