### ISSUE TITLE
[Bug]: LSE-py引擎和系统py冲突导致崩服

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#136]
### Describe the bug

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/b4c36bf2-6529-4f82-8b6e-8cb6d89e44d7)
[crash.zip](https://github.com/LiteLDev/LegacyScriptEngine/files/15381166/crash.zip)

LSE-py引擎和系统py冲突导致崩服

### To Reproduce

系统装py

### Expected behavior

在LL2中，LLSE的py引擎并不会和系统py冲突，希望修复

### Screenshots

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/b4c36bf2-6529-4f82-8b6e-8cb6d89e44d7)

### Platform

Win10

### BDS Version

1.20.81

### LeviLamina Version

0.12.3

### LegacyScriptEngine Version

0.7.11

**Comment by ShrBox** [comment]
无法解决，因为是新版本Python与老版本之间的冲突，你现在去搞个LL2的环境也会崩
