### ISSUE TITLE
[Bug]: Offline Economic Function

### ISSUE THREAD

**Issue by Caldron47** [LiteLDev/LegacyScriptEngine#139]
### Describe the bug

money.get(), money.add(), money.reduce(), etc throws not a function error when used in onMoneyTrans event

### To Reproduce

```js
mc.listen('onMoneyTrans', function(from, to, money) {
let mon = money.get(from);
});
```
will throw the error.

### Expected behavior

All money functions can be used in money trans event.

### Platform

Windows 10

### BDS Version

1.20.81

### LeviLamina Version

0.12.3

### LegacyScriptEngine Version

0.7.12

**Comment by ShrBox** [comment]
![图片](https://github.com/LiteLDev/LegacyScriptEngine/assets/53301243/6f9f48dc-c273-49d3-81ae-05d7d69716e6)
I can't reproduce it.

**Comment by ShrBox** [comment]
According to your code, `money` is a variable.

**Comment by Caldron47** [comment]
> ![图片](https://private-user-images.githubusercontent.com/53301243/333799822-6f9f48dc-c273-49d3-81ae-05d7d69716e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY2NDA2MDQsIm5iZiI6MTcxNjY0MDMwNCwicGF0aCI6Ii81MzMwMTI0My8zMzM3OTk4MjItNmY5ZjQ4ZGMtYzI3My00OWQzLTgxYWUtMDVkN2Q2OTcxNmU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI1VDEyMzE0NFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFlMGQ0YjhhODAxNmQ0YTYwOTZjZDdiMDUwNDQ5Y2M5NzZmZDliYmI3NDA2Y2U4MjA4YjAzOGFlODZiOGYwMTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Z-oApc-SVZovbIHboHqNbbgtuzKZ_B6KKgxFoq63pu8) I can't reproduce it.

Sorry i just realized it only happens in onMoneyTrans event

**Comment by Caldron47** [comment]
> According to your code, `money` is a variable.

Oh wait.. you are right 💀
