### ISSUE TITLE
[Bug]: quickEvalMolangScript crash server

### ISSUE THREAD

**Issue by MyNameInc** [LiteLDev/LegacyScriptEngine#141]
### Describe the bug

crash server

### To Reproduce

mc.regPlayerCmd("v", "v", function (pl, args) {
    pl.quickEvalMolangScript("v.test = 1.0;")  
})
mc.regPlayerCmd("q", "q", function (pl, args) {
    pl.quickEvalMolangScript("q.variant;")  
})

### Expected behavior

crash server

### Platform

windows 10

### BDS Version

1.20.81

### LeviLamina Version

0.12.3

### LegacyScriptEngine Version

0.7.12

**Comment by ShrBox** [comment]
Fixed in https://github.com/LiteLDev/LeviLamina/commit/6ed404f06f3d00b0c9e47250807caae43f73b959
