### ISSUE TITLE
[Feature]: 优化玩家数据库

### ISSUE THREAD

**Issue by mingjigege** [LiteLDev/LegacyScriptEngine#142]
### Is your feature request related to a problem? Please describe.

玩家数据库竟然会存假人数据

### Describe the solution you'd like

玩家数据库不再存储假人数据
数据库新增API —— 删除存储的玩家数据（方便删除假人数据）

**Comment by ShrBox** [comment]
PlayerInfo由LeviLamina提供，并非由LSE进行管理
