### ISSUE TITLE
[Bug]: Intercepting onSpawnProjectile reduces the item

### ISSUE THREAD

**Issue by Caldron47** [LiteLDev/LegacyScriptEngine#143]
### Describe the bug

When intercepting onSpawnProjectile event, the projectile doesn't get spawned but the number of item gets reduced.

### To Reproduce

```js
mc.listen('onSpawnProjectile', function(shooter, type) {
     return false;
});
```
Throw a trident/snowball/ender pearl/etc. It will be gone or reduced by 1

### Expected behavior

I believe the number of item should stay the same if the event is intercepted.

### Platform

Windows 10

### BDS Version

1.20.81

### LeviLamina Version

0.12.3

### LegacyScriptEngine Version

0.7.12

**Comment by ShrBox** [comment]
I have fix it for trident.
You can block snowball or something else's using by `onUseItem` from reducing them.
