### ISSUE TITLE
[Bug]: File.rename(from,to)重命名文件后文件消失（被删除？）

### ISSUE THREAD

**Issue by Atrium4641** [LiteLDev/LegacyScriptEngine#147]
### Describe the bug

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/173249132/90da9701-b5db-4a9d-bd8c-b0c69db8fd30)

重命名指定文件 / 文件夹
File.rename(from,to)

参数：
from : String
文件 / 文件夹的旧名字

to : String
新名字

返回值：是否复制成功
返回值类型：Boolean

[Bug]: File.rename(from,to)重命名文件后文件消失（被删除？）

正常情况是应该正常重命名

比如重命名名为config.json为config.json.bak，但是config.json直接被删除了

### To Reproduce

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/173249132/c78010f7-412f-41be-829b-1e619fa79855)

正常情况是应该正常重命名

### Expected behavior

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/173249132/e8915df8-eee3-4a90-9bb0-52cc76ef5b65)

[Bug]: File.rename(from,to)重命名文件后文件消失（被删除？）

正常情况是应该正常重命名

### Screenshots

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/173249132/2c7ec3c9-1bcb-4102-95f2-a3101885463c)

[Bug]: File.rename(from,to)重命名文件后文件消失（被删除？）

### Platform

Win10

### BDS Version

1.21.1

### LeviLamina Version

0.13.3

### LegacyScriptEngine Version

0.8.1

### Additional context

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/173249132/a8db0043-f84e-42e9-a8ef-1ceba403b51f)

**Comment by ShrBox** [comment]
无法复现
