### ISSUE TITLE
[Bug]: Null pointer in toSNBT

### ISSUE THREAD

**Issue by Atrium4641** [LiteLDev/LegacyScriptEngine#148]
### Describe the bug

![bd6dffbe1d656e2aa64d338a96164b58_720](https://github.com/LiteLDev/LegacyScriptEngine/assets/173249132/d8d6957e-9c6d-4bce-b4fa-0d2f1ecd46a1)

插件地址：https://www.minebbs.com/resources/storagehelper.7765/

### To Reproduce

![bd6dffbe1d656e2aa64d338a96164b58_720](https://github.com/LiteLDev/LegacyScriptEngine/assets/173249132/1c2707fc-f667-426b-86e2-f4b1729a241c)

插件地址：https://www.minebbs.com/resources/storagehelper.7765/

### Expected behavior

正常使用 不报错

### Screenshots

![bd6dffbe1d656e2aa64d338a96164b58_720](https://github.com/LiteLDev/LegacyScriptEngine/assets/173249132/86e044a6-ad31-4560-914d-99a781336d43)

### Platform

Win10

### BDS Version

1.21.1

### LeviLamina Version

0.13.3

### LegacyScriptEngine Version

0.8.1

### Additional context

![bd6dffbe1d656e2aa64d338a96164b58_720](https://github.com/LiteLDev/LegacyScriptEngine/assets/173249132/49e42b02-f5c2-46f3-82dd-9d227f668302)

**Comment by ShrBox** [comment]
这种使用第三方API的难以复现的问题我无能为力
我建议在能复现的环境中从[release](https://github.com/LiteLDev/LegacyScriptEngine/releases)下载`legacy-script-engine-quickjs-windows-x64.zip`并将其中的`legacy-script-engine-quickjs.pdb`放入`plugins/legacy-script-engine-quickjs/`文件夹中，然后使用x64dbg, windbg或visual studio挂载调试器，并将错误发生时调试器的堆栈信息截图

**Comment by ShrBox** [comment]
可能在 dd9f9feac94ac16bdc4f9eb72ca92de11f7696a2 中已经修复，如果在0.8.12中还能复现此问题请回复
It may have been fixed in dd9f9feac94ac16bdc4f9eb72ca92de11f7696a2. Please reply if you can still reproduce this problem in 0.8.12.
