### ISSUE TITLE
[Bug]: name2uuid和name2xuid无法使用

### ISSUE THREAD

**Issue by FtyLollipop** [LiteLDev/LegacyScriptEngine#150]
### Describe the bug

name2uuid和name2xuid两个API返回值为空

### To Reproduce

传入已进服过的玩家名，返回值为空

### Expected behavior

正常返回uuid或xuid

### Platform

Windows 11

### BDS Version

1.21.1.03

### LeviLamina Version

0.13.3

### LegacyScriptEngine Version

0.8.1

**Comment by ShrBox** [comment]
打开`./plugins/LeviLamina/config/config.json`中的`playerInfo`->`alwaysLaunch`
