### ISSUE TITLE
[Bug]: 重载/卸载插件报错

### ISSUE THREAD

**Issue by zimuya4153** [LiteLDev/LegacyScriptEngine#151]
### Describe the bug

重载/卸载插件时，会出现以下报错，并且插件被卸载
![image](https://github.com/user-attachments/assets/01f9c337-6fee-43ac-aab9-641b31b6936f)

### To Reproduce

装上此插件开启服务器后，后台执行命令`ll reload ShorcutCommand`
[ShorcutCommand.zip](https://github.com/user-attachments/files/16201153/ShorcutCommand.zip)

### Expected behavior

修复这个bug

### Screenshots

![image](https://github.com/user-attachments/assets/08ef4180-28d0-4128-8176-f5cee3325b2c)
![image](https://github.com/user-attachments/assets/5bb692e4-f19f-40c6-855d-ec9be91f69b6)

### Platform

Windows 10

### BDS Version

1.21.1-3.685+f2ce140

### LeviLamina Version

LeviLamina-0.13.1+123135e8e

### LegacyScriptEngine Version

0.8.0

**Comment by ShrBox** [comment]
https://github.com/LiteLDev/LeviLamina/releases/tag/v0.13.2
你猜猜LeviLamina 0.13.2的更新日志里面有什么
> Fix unload
