### ISSUE TITLE
[Bug]: Source actor becomes a wild pointer when Actor falls to die in onMobHurt

### ISSUE THREAD

**Issue by panjj95** [LiteLDev/LegacyScriptEngine#157]
### Describe the bug

Source actor becomes a wild pointer when Actor falls to die in onMobHurt.

### To Reproduce

```js
mc.listen('onMobHurt', ()=>{})
```

### Expected behavior

It works  fine.

### Platform

Windows 10

### BDS Version

1.21.3.01

### LeviLamina Version

0.13.4

### LegacyScriptEngine Version

0.8.5

### Additional context

[trace_2024-08-02_03-31-52.log](https://github.com/user-attachments/files/16464714/trace_2024-08-02_03-31-52.log)
日志
[minidump_2024-08-02_03-31-52.dmp](https://github.com/user-attachments/files/16464716/minidump_2024-08-02_03-31-52.dmp)

**Comment by ShrBox** [comment]
有用SimulatedPlayer(模拟玩家)吗，看起来是一个LSE插件在onMobHurt将其中的source Entity对象转为Player对象后，调用getDevice后，LSE在调用getOrCreateUniqueID函数时出现了异常
![image](https://github.com/user-attachments/assets/bb2b1da9-4b1c-425f-b441-a3081746153c)

**Comment by panjj95** [comment]
> 有用SimulatedPlayer（模拟玩家）吗，看起来是一个LSE插件在onMobHurt将其中的source Entity对象转为Player对象后，调用getDevice后，LSE在调用getOrCreateUniqueID函数时出现了异常 ![image](https://private-user-images.githubusercontent.com/53301243/354463654-bb2b1da9-4b1c-425f-b441-a3081746153c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzM0NjYsIm5iZiI6MTcyMjU3MzE2NiwicGF0aCI6Ii81MzMwMTI0My8zNTQ0NjM2NTQtYmIyYjFkYTktNGIxYy00MjVmLWI0NDEtYTMwODE3NDYxNTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA0MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNGU0ZTg0Y2I4MGE0ZjA4MGFkYjdiNDUzYzE3NTkwMDdiY2FjODgwZWI2NmQyZGQxZTA1MjQ5MmM2NGE5ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFu40bW7L57Qf-8XsyEaryEoRMPd_1X5vfCMeAuo980)

没有用假人插件，这很难排查

**Comment by ShrBox** [comment]
> > 有用SimulatedPlayer（模拟玩家）吗，看起来是一个LSE插件在onMobHurt将其中的source Entity对象转为Player对象后，调用getDevice后，LSE在调用getOrCreateUniqueID函数时出现了异常 ![image](https://private-user-images.githubusercontent.com/53301243/354463654-bb2b1da9-4b1c-425f-b441-a3081746153c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjI1NzM0NjYsIm5iZiI6MTcyMjU3MzE2NiwicGF0aCI6Ii81MzMwMTI0My8zNTQ0NjM2NTQtYmIyYjFkYTktNGIxYy00MjVmLWI0NDEtYTMwODE3NDYxNTNjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODAyVDA0MzI0NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTVjNGU0ZTg0Y2I4MGE0ZjA4MGFkYjdiNDUzYzE3NTkwMDdiY2FjODgwZWI2NmQyZGQxZTA1MjQ5MmM2NGE5ZjcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.bFu40bW7L57Qf-8XsyEaryEoRMPd_1X5vfCMeAuo980)
> 
> 没有用假人插件，这很难排查

看看哪些QuickJs插件在onMobHurt里面调用了getDevice，把插件链接发我

**Comment by panjj95** [comment]
[trace_2024-08-02_14-37-08.zip](https://github.com/user-attachments/files/16466521/trace_2024-08-02_14-37-08.zip)
插件
[plugins.zip](https://github.com/user-attachments/files/16466602/plugins.zip)

**Comment by panjj95** [comment]
[trace_2024-08-07_00-55-39.log](https://github.com/user-attachments/files/16518212/trace_2024-08-07_00-55-39.log)
关于legacy-script-engine-lua.dll的日志
[minidump_2024-08-07_00-55-39.dmp](https://github.com/user-attachments/files/16518223/minidump_2024-08-07_00-55-39.dmp)
lse版本0.8.10

**Comment by ShrBox** [comment]
改了下DeviceAPI令人摸不着头脑的构造函数，待会儿发0.8.11，应该不会再崩了

**Comment by panjj95** [comment]
[log (2).zip](https://github.com/user-attachments/files/16542266/log.2.zip)

**Comment by ShrBox** [comment]
请尝试升级0.8.14，怀疑与 #160 同源

**Comment by panjj95** [comment]
[trace_2024-08-09_07-38-04.log](https://github.com/user-attachments/files/16556029/trace_2024-08-09_07-38-04.log)
0.8.14
[minidump_2024-08-09_07-38-04.dmp](https://github.com/user-attachments/files/16556033/minidump_2024-08-09_07-38-04.dmp)

**Comment by ShrBox** [comment]
0.8.15已经将EntityAPI, PlayerAPI以及DeviceAPI的存储内容改为ActorRuntimeID，尝试升级0.8.15

**Comment by panjj95** [comment]
> 0.8.15已经将EntityAPI， PlayerAPI以及DeviceAPI的存储内容改为ActorRuntimeID，尝试升级0.8.15

[server-latest.log](https://github.com/user-attachments/files/16563530/server-latest.log)

**Comment by ShrBox** [comment]
请尝试升级0.8.16，理论上已经修复了此问题

**Comment by panjj95** [comment]
> 请尝试升级0.8.16，理论上已经修复了此问题

[server-latest.log](https://github.com/user-attachments/files/16568488/server-latest.log)

**Comment by ShrBox** [comment]
试试这个actions版本 https://github.com/liteldev/LegacyScriptEngine/actions/runs/10330148200

**Comment by panjj95** [comment]
[trace_2024-08-11_10-48-53.zip](https://github.com/user-attachments/files/16571570/trace_2024-08-11_10-48-53.zip)

**Comment by ShrBox** [comment]
> [trace_2024-08-11_10-48-53.zip](https://github.com/user-attachments/files/16571570/trace_2024-08-11_10-48-53.zip)

此错误已经不属于该Issue的范围，故关闭此Issue

**Comment by panjj95** [comment]
> 试试0.8.17

[4.zip](https://github.com/user-attachments/files/16575606/4.zip)

**Comment by ShrBox** [comment]
此问题已在0.8.18彻底解决
