### ISSUE TITLE
[Feature]: LSE文档部分描述有误

### ISSUE THREAD

**Issue by Atrium4641** [LiteLDev/LegacyScriptEngine#189]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/4800ba83-ce5c-45e8-9a86-4476d47a931d)
it.damage 实际上并不是物品当前耐久，而是当前物品所已使用（已消耗）耐久，实际物品当前耐久应该是(it.maxDamage - it.damage)

![image](https://github.com/user-attachments/assets/08b21e58-b29e-42fe-9453-dd4b388195bf)
实际上6才是旁观者模式，而且player.setGameMode(6)和player.setGameMode(3)都无法设置玩家为旁观者模式

### Describe the solution you'd like

1

### Describe alternatives you've considered

1

### Additional context

1

**Comment by ShrBox** [comment]
a4d45ade7fdf9abfc349559ad81cc1be1c656511
