### ISSUE TITLE
[Feature]: 希望增加一个保存结构NBT的API

### ISSUE THREAD

**Issue by Atrium4641** [LiteLDev/LegacyScriptEngine#191]
### Is your feature request related to a problem? Please describe.

![image](https://github.com/user-attachments/assets/2f4635b1-f9cf-43e8-b4fe-330251c7273b)

目前LSE只有获取和设置，希望增加一个保存结构NBT的API，可以保存主世界、下界、末地的那种

希望增加一个保存结构NBT的API

### Describe the solution you'd like

![image](https://github.com/user-attachments/assets/2f4635b1-f9cf-43e8-b4fe-330251c7273b)

目前LSE只有获取和设置，希望增加一个保存结构NBT的API，可以保存主世界、下界、末地的那种

希望增加一个保存结构NBT的API

### Describe alternatives you've considered

![image](https://github.com/user-attachments/assets/2f4635b1-f9cf-43e8-b4fe-330251c7273b)

目前LSE只有获取和设置，希望增加一个保存结构NBT的API，可以保存主世界、下界、末地的那种

希望增加一个保存结构NBT的API

### Additional context

![image](https://github.com/user-attachments/assets/2f4635b1-f9cf-43e8-b4fe-330251c7273b)

目前LSE只有获取和设置，希望增加一个保存结构NBT的API，可以保存主世界、下界、末地的那种

希望增加一个保存结构NBT的API

**Comment by ShrBox** [comment]
LegacyScriptEngine已进入仅维护状态，不再新增任何API
