### ISSUE TITLE
[Bug]: 疑似与FishingAC冲突

### ISSUE THREAD

**Issue by PHEyejixHello** [LiteLDev/LegacyScriptEngine#21]
### Describe the bug

23:21:26.730 ERROR [LeviLamina] Error in [ll::event::Listener<class ll::event::player::PlayerJoinEvent>:26] of <unknown plugin>:
23:21:26.746 ERROR [LeviLamina] Raw Seh Exception:
23:21:26.746 ERROR [LeviLamina] [0xC0000005:ntstatus] 0x%p 指令引用了 0x%p 内存。该内存不能为 %s。
23:21:26.746 ERROR [LeviLamina] Parameter 0: 0x0
23:21:26.746 ERROR [LeviLamina] Parameter 1: 0xffffffffffffffff
23:21:26.762 ERROR [LeviLamina] exception stacktrace:
23:21:26.762 ERROR [LeviLamina]  0> at: 0x7FF8A42B63BD LeviLamina -> std::_Adjust_manually_vector_aligned + 0x3D [xmemory:160L]
23:21:26.762 ERROR [LeviLamina]  1> at: 0x7FF8A4299200 LeviLamina -> std::_Deallocate<16,0> + 0x40 [xmemory:265L]
23:21:26.762 ERROR [LeviLamina]  2> at: 0x7FF8A42C5112 LeviLamina -> std::allocator<char>::deallocate + 0x22 [xmemory:970L]
23:21:26.762 ERROR [LeviLamina]  3> at: 0x7FF8A42C067F LeviLamina -> std::basic_string<char,std::char_traits<char>,std::allocator<char> >::_Tidy_deallocate + 0x7F [xstring:4841L]
23:21:26.762 ERROR [LeviLamina]  4> at: 0x7FF8A42B3313 LeviLamina -> std::basic_string<char,std::char_traits<char>,std::allocator<char> >::~basic_string<char,std::char_traits<char>,std::allocator<char> > + 0x13 [xstring:3119L]
23:21:26.762 ERROR [LeviLamina]  5> at: 0x7FF8A461B453 LeviLamina -> `Player::getRealName'::`1'::dtor$0 + 0x23
23:21:26.762 ERROR [LeviLamina]  6> at: 0x7FF8B9441030 VCRUNTIME140_1 + 0x1030
23:21:26.762 ERROR [LeviLamina]  7> at: 0x7FF8B9442CF3 VCRUNTIME140_1 + 0x2CF3
23:21:26.762 ERROR [LeviLamina]  8> at: 0x7FF8B9443B75 VCRUNTIME140_1 + 0x3B75
23:21:26.762 ERROR [LeviLamina]  9> at: 0x7FF8B944225C VCRUNTIME140_1 + 0x225C
23:21:26.762 ERROR [LeviLamina] 10> at: 0x7FF8B9442389 VCRUNTIME140_1 + 0x2389
23:21:26.777 ERROR [LeviLamina] 11> at: 0x7FF8B9444189 VCRUNTIME140_1 + 0x4189
23:21:26.777 ERROR [LeviLamina] 12> at: 0x7FF8A45BF158 LeviLamina -> __GSHandlerCheck_EH4 + 0x64 [gshandlereh4.cpp:86L]
23:21:26.777 ERROR [LeviLamina] 13> at: 0x7FF8CA23481F ntdll + 0xA481F
23:21:26.777 ERROR [LeviLamina] 14> at: 0x7FF8CA19600C ntdll + 0x600C
23:21:26.777 ERROR [LeviLamina] 15> at: 0x7FF8B9443E16 VCRUNTIME140_1 + 0x3E16
23:21:26.777 ERROR [LeviLamina] 16> at: 0x7FF8B9441635 VCRUNTIME140_1 + 0x1635
23:21:26.777 ERROR [LeviLamina] 17> at: 0x7FF8B9441D6C VCRUNTIME140_1 + 0x1D6C
23:21:26.777 ERROR [LeviLamina] 18> at: 0x7FF8B9441AEA VCRUNTIME140_1 + 0x1AEA
23:21:26.777 ERROR [LeviLamina] 19> at: 0x7FF8B944232F VCRUNTIME140_1 + 0x232F
23:21:26.777 ERROR [LeviLamina] 20> at: 0x7FF8B9442389 VCRUNTIME140_1 + 0x2389
23:21:26.777 ERROR [LeviLamina] 21> at: 0x7FF8B9444189 VCRUNTIME140_1 + 0x4189
23:21:26.777 ERROR [LeviLamina] 22> at: 0x7FF8A45BF158 LeviLamina -> __GSHandlerCheck_EH4 + 0x64 [gshandlereh4.cpp:86L]
23:21:26.777 ERROR [LeviLamina] 23> at: 0x7FF8CA23479F ntdll + 0xA479F
23:21:26.793 ERROR [LeviLamina] 24> at: 0x7FF8CA194BEF ntdll + 0x4BEF
23:21:26.793 ERROR [LeviLamina] 25> at: 0x7FF8CA23350E ntdll + 0xA350E
23:21:26.793 ERROR [LeviLamina] 26> at: 0x7FF8B943118D VCRUNTIME140 + 0x1118D
23:21:26.793 ERROR [LeviLamina] 27> at: 0x7FF8A42C7388 LeviLamina -> std::_Char_traits<char,int>::move + 0x128 [xstring:122L]
23:21:26.793 ERROR [LeviLamina] 28> at: 0x7FF8A42C3777 LeviLamina -> std::basic_string<char,std::char_traits<char>,std::allocator<char> >::assign + 0x57 [xstring:3381L]
23:21:26.809 ERROR [LeviLamina] 29> at: 0x7FF8A42B4027 LeviLamina -> std::basic_string<char,std::char_traits<char>,std::allocator<char> >::operator= + 0x87 [xstring:3193L]
23:21:26.809 ERROR [LeviLamina] 30> at: 0x7FF8A451908B LeviLamina -> Player::getRealName + 0xDB [Player.cpp:67L]
23:21:26.809 ERROR [LeviLamina] 31> at: 0x7FF8A43F80ED LeviLamina -> `ll::service::PlayerInfo::Impl::Impl'::`2'::<lambda_2>::operator() + 0xCD [PlayerInfo.cpp:50L]
23:21:26.809 ERROR [LeviLamina] 32> at: 0x7FF8A43F558D LeviLamina -> std::invoke<`ll::service::PlayerInfo::Impl::Impl'::`2'::<lambda_2> &,ll::event::player::PlayerJoinEvent &> + 0x1D [type_traits:1777L]
23:21:26.809 ERROR [LeviLamina] 33> at: 0x7FF8A43F9844 LeviLamina -> std::_Func_impl_no_alloc<`ll::service::PlayerInfo::Impl::Impl'::`2'::<lambda_2>,void,ll::event::player::PlayerJoinEvent &>::_Do_call + 0x24 [functional:843L]
23:21:26.809 ERROR [LeviLamina] 34> at: 0x7FF8A43F87C2 LeviLamina -> std::_Func_class<void,ll::event::player::PlayerJoinEvent &>::operator() + 0x52 [functional:884L]
23:21:26.809 ERROR [LeviLamina] 35> at: 0x7FF8A43FC60B LeviLamina -> ll::event::Listener<ll::event::player::PlayerJoinEvent>::call + 0x2B [Listener.h:24L]
23:21:26.809 ERROR [LeviLamina] 36> at: 0x7FF8A4314E15 LeviLamina -> ll::event::CallbackStream::publish + 0xD5 [EventBus.cpp:35L]
23:21:26.809 ERROR [LeviLamina] 37> at: 0x7FF8A4300747 LeviLamina -> ll::event::EventBus::publish + 0x117 [EventBus.cpp:151L]
23:21:26.824 ERROR [LeviLamina] 38> at: 0x7FF8A432432D LeviLamina -> ll::event::EventBus::publish<ll::event::player::PlayerJoinEvent &> + 0x3D [EventBus.h:40L]
23:21:26.824 ERROR [LeviLamina] 39> at: 0x7FF8A4323E12 LeviLamina -> ll::event::player::PlayerJoinEventHook::detour + 0x32 [PlayerJoinEvent.cpp:16L]
23:21:26.824 ERROR [LeviLamina] 40> at: 0x7FF60278C0B4 bedrock_server_mod -> NetworkSystem::_sortAndPacketizeEvents + 0x7A4
23:21:26.824 ERROR [LeviLamina] 41> at: 0x7FF602780E24 bedrock_server_mod -> <lambda_6b5fe2731cb32d396a02753373eb3610>::operator() + 0x214
23:21:26.840 ERROR [LeviLamina] 42> at: 0x7FF60279DCA8 bedrock_server_mod -> NetworkSystem::runEvents + 0x268
23:21:26.840 ERROR [LeviLamina] 43> at: 0x7FF60354C5AF bedrock_server_mod -> Minecraft::update + 0x134F
23:21:26.840 ERROR [LeviLamina] 44> at: 0x7FF602ACC832 bedrock_server_mod -> ServerInstance::_update + 0xF2
23:21:26.840 ERROR [LeviLamina] 45> at: 0x7FF602ABC7FA bedrock_server_mod -> <lambda_56977c8f513937af2eebbbd13c37f013>::operator() + 0x4CA
23:21:26.840 ERROR [LeviLamina] 46> at: 0x7FF602A841DE bedrock_server_mod -> std::thread::_Invoke<std::tuple<<lambda_56977c8f513937af2eebbbd13c37f013> >,0> + 0xE
23:21:26.840 ERROR [LeviLamina] 47> at: 0x7FF8C6D11FFA ucrtbase + 0x21FFA
23:21:26.840 ERROR [LeviLamina] 48> at: 0x7FF8C7597974 KERNEL32 + 0x17974
23:21:26.840 ERROR [LeviLamina] 49> at: 0x7FF8CA1FA271 ntdll + 0x6A271

### To Reproduce

装载LSE和FishingAc后玩家进服

### Expected behavior

报错，但不崩

### Platform

win2019

### BDS Version

1.20.51

### LeviLamina Version

0.6.3

### LegacyScriptEngine Version

0.13

**Comment by ShrBox** [comment]
FAC是闭源插件，我们并不能知道FAC对玩家对象做了什么操作，所以我们无法解决
