### ISSUE TITLE
[Bug]: dv.ip 无法正常获取到玩家的IP

### ISSUE THREAD

**Issue by PHEyejixHello** [LiteLDev/LegacyScriptEngine#22]
### Describe the bug

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/123708464/16fdb450-1008-4d5b-91ef-e7915a06f89b)

无法正常获取到IP

log出来为空

### To Reproduce

无法正常获取到IP

### Expected behavior

无法正常获取到IP

**Comment by ShrBox** [comment]
Fixed in f7bcafe88ac3a9046b1acf079479bb2a348e4b9f
