### ISSUE TITLE
[Bug]: item.set is not working

### ISSUE THREAD

**Issue by Hosiyume** [LiteLDev/LegacyScriptEngine#31]
### Describe the bug

`item.set` funtion is not working

### To Reproduce

1. Use these codes
```js
let player = ...;
let hand = player.getHand();
let item = mc.newItem("minecraft:dirt", 1);
hand.set(item);
player.refreshItems();
```
2. Trigger it

### Expected behavior

The item should be converted into dirt

### BDS Version

1.20.51.01

### LeviLamina Version

0.7.2

### LegacyScriptEngine Version

0.2.4

**Comment by xianyubb** [comment]
I think you're just manipulating on variables, not on player.

**Comment by Hosiyume** [comment]
> I think you're just manipulating on variables, not on player.

wrong, this should be a reference

**Comment by cnlancehu** [comment]
the same problem is happening on my server

the funtion is not working but it still returns `true`

while the other functions like `addItemToFirstEmptySlot` `addItem` could run properly

**Comment by Hurry1027** [comment]
同样的问题
pl.getHand().set(mc.newItem("minecraft:apple", 1))
pl.refreshItems()
获取不到物品。

**Comment by Hosiyume** [comment]
#37
