### ISSUE TITLE
[Bug]: 文档链接无法正常跳转

### ISSUE THREAD

**Issue by HuoHuas001** [LiteLDev/LegacyScriptEngine#34]
### Describe the bug

![443C8001E71A1F27792A5DD3182C8B75](https://github.com/LiteLDev/LegacyScriptEngine/assets/51258524/63a79bcb-b6b5-4df9-88df-0a5a1102313e)
文档内的这些链接无法正确跳转到所指向的内容，会跳转到404页面

### To Reproduce

点击链接跳转

### Expected behavior

链接无法正确跳转到所指向的内容

### Screenshots

![443C8001E71A1F27792A5DD3182C8B75](https://github.com/LiteLDev/LegacyScriptEngine/assets/51258524/63a79bcb-b6b5-4df9-88df-0a5a1102313e)

### Platform

Windows11

**Comment by twoone-3** [comment]
修了，看看
