### ISSUE TITLE
[Bug]: onScoreChange事件失效

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#41]
### Describe the bug

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/c65f50d4-4668-4543-90a9-109459665933)

onScoreChange监听事件无法正常生效，没有任何反应，不会执行之后的代码

### To Reproduce

创建一个js使用onScoreChanged监听并打印一些数值

### Expected behavior

正常打印玩家的计分板数值

### Screenshots

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/1ec113b5-9087-4ce4-b44b-ddb7af172b0d)

### Platform

Windows10

### BDS Version

1.20.62

### LeviLamina Version

0.8.3

### LegacyScriptEngine Version

0.3.1

**Comment by ShrBox** [comment]
此事件还没被加入到LSE中，在计划之中

**Comment by yufengya0420** [comment]
> 此事件还没被加入到LSE中，在计划之中

好的

**Comment by Caldron47** [comment]
> This event has not been added to LSE yet, it is planned

When will this event get added? :D

**Comment by ShrBox** [comment]
Added in e851bfae1055ab68849dbd1ea14a7402783bd93a
