### ISSUE TITLE
[Bug]: 无法获取玩家视线方向的实体和方块

### ISSUE THREAD

**Issue by TRDSCSH** [LiteLDev/LegacyScriptEngine#42]
### Describe the bug

无法使用 `pl.getBlockFromViewVector()` 和 `pl.getEntityFromViewVector()` 获取玩家视线方向方块和实体，总是返回空。

### To Reproduce

在服务端装载以下 JS 插件，它的主要作用是持续检测每个玩家视线方向的方块和实体。
```JavaScript
let onlinePlayers = new Array;

mc.listen("onServerStarted", () => {
    setInterval(() => { // 核心代码：持续检测每个玩家视线方向的方块和实体
        for (let i = 0; i < onlinePlayers.length; i++) {
            const pl = onlinePlayers[i];
            const blockFromViewVector = pl.getBlockFromViewVector(false, false, 100.0, false);
            const entityFromViewVector = pl.getEntityFromViewVector(100.0);
            log(blockFromViewVector);
            if (blockFromViewVector) log(blockFromViewVector.type);
            log(entityFromViewVector);
            if (entityFromViewVector) log(entityFromViewVector.type);
        }
    }, 1000);
});

mc.listen("onJoin", (pl) => {
    setTimeout(() => {
        onlinePlayers = mc.getOnlinePlayers();
    }, 1000);
});

mc.listen("onLeft", (pl) => {
    setTimeout(() => {
        onlinePlayers = mc.getOnlinePlayers();
    }, 1000);
});
```

开服后，玩家进服务器，看向任意实体和方块，即可发现无论看向什么方向，它总是返回空。

下面是我的操作。

视线方向如下图所示（垂直向下近距离俯视在铁轨上的矿车）：
![垂直向下近距离俯视在铁轨上的矿车](https://github.com/LiteLDev/LegacyScriptEngine/assets/125717891/14adab7b-1ff2-43bd-8493-3c8aad35eff5)

观察服务端，发现代码运行结果类似以下（结果是没有获取到视线方向的方块和实体）：
```
23:17:36.519 INFO [TestPlugin] <Null>

23:17:36.520 INFO [TestPlugin] <Null>

```

### Expected behavior

当视线方向如上图时，应该有类似以下的输出（这段运行结果是在 LiteLoaderBDS 上通过类似操作得到的）：
```
22:53:58 INFO [Test] <Block>
22:53:58 INFO [Test] minecraft:rail
22:53:58 INFO [Test] <Entity>
22:53:58 INFO [Test] minecraft:minecart
```

### Platform

Windows Server 2022 Datacenter

### BDS Version

1.20.62.02

### LeviLamina Version

0.8.3

### LegacyScriptEngine Version

0.3.1

**Comment by ShrBox** [comment]
Fixed in 2fc2472e8382c51c0248c48ddf0ff7d2db8f81e4
![图片](https://github.com/LiteLDev/LegacyScriptEngine/assets/53301243/274151ff-2898-4470-a7ae-f3c69e9b91de)

**Comment by ShrBox** [comment]
有点摸不着头脑，这个先鸽了，等有空再修

**Comment by ShrBox** [comment]
Fixed https://github.com/LiteLDev/LeviLamina/issues/1481
