### ISSUE TITLE
[Bug]: 循环发送pl.setBossBar导致客户端崩溃

### ISSUE THREAD

**Issue by Hurry1027** [LiteLDev/LegacyScriptEngine#49]
### Describe the bug

quickjs音乐插件需要用bossbar来显示歌词，
循环发送pl.setBossBar，
玩家客户端显示 “发送了错误的数据包”然后崩溃。

### To Reproduce

**test.js**

```
let count = 0;
setInterval(()=>{
    mc.getOnlinePlayers().forEach(pl => {
        count++;
        pl.setBossBar(1027,`设置次数: ${count}`, 50, 0);
    });
},100)
```
持续执行一段时间后，客户端显示 “发送了错误的数据包”，然后崩溃。
在LL2quickjs插件中这段代码可以正常运行。

### Expected behavior

不崩溃。

### BDS Version

1.20.62.02

### LeviLamina Version

0.9.0

### LegacyScriptEngine Version

0.4.0

**Comment by TRDSCSH** [comment]
使用 `setBossBar` 时仍然存在问题：当内容为一些字符串时，玩家客户端将会显示 “服务端发送了破损的数据包”。

使用的各模块的版本都是最新：LL 0.9.0 | LSE 0.4.1 | LegacyRemoteCall 0.4.0 | LegacyParticleAPI 0.4.0 | LegacyMoney 0.4.0

我测试并找到了一些导致异常的字符串：`[出现异常的文本。]` `str:这是一句中文！` `Bing 搜索引擎?`

可以使用以下 JS 插件复现 Bug：
```JavaScript
let onlinePlayers = new Array;

setInterval(() => {
    for (let i = 0; i < onlinePlayers.length; i++) {
        const pl = onlinePlayers[i];
        pl.setBossBar(10000/*uid*/, "Bing 搜索引擎?"/*content*/, 100/*percent*/, 0/*colour*/);
        // [出现异常的文本。]
        // str:这是一句中文！
        // Bing 搜索引擎?
    }
}, 1000);

mc.listen("onJoin", (pl) => {
    setTimeout(() => {
        onlinePlayers = mc.getOnlinePlayers();
        pl.tell("Test");
    }, 2000);
});

mc.listen("onLeft", (pl) => {
    onlinePlayers = mc.getOnlinePlayers();
});
```

@ShrBox

**Comment by ShrBox** [comment]
> 使用 `setBossBar` 时仍然存在问题：当内容为一些字符串时，玩家客户端将会显示 “服务端发送了破损的数据包”。
> 
> 使用的各模块的版本都是最新：LL 0.9.0 | LSE 0.4.1 | LegacyRemoteCall 0.4.0 | LegacyParticleAPI 0.4.0 | LegacyMoney 0.4.0
> 
> 我测试并找到了一些导致异常的字符串：`[出现异常的文本。]` `str:这是一句中文！` `Bing 搜索引擎?`
> 
> 可以使用以下 JS 插件复现 Bug：
> 
> ```js
> let onlinePlayers = new Array;
> 
> setInterval(() => {
>     for (let i = 0; i < onlinePlayers.length; i++) {
>         const pl = onlinePlayers[i];
>         pl.setBossBar(10000/*uid*/, "Bing 搜索引擎?"/*content*/, 100/*percent*/, 0/*colour*/);
>         // [出现异常的文本。]
>         // str:这是一句中文！
>         // Bing 搜索引擎?
>     }
> }, 1000);
> 
> mc.listen("onJoin", (pl) => {
>     setTimeout(() => {
>         onlinePlayers = mc.getOnlinePlayers();
>         pl.tell("Test");
>     }, 2000);
> });
> 
> mc.listen("onLeft", (pl) => {
>     onlinePlayers = mc.getOnlinePlayers();
> });
> ```
> 
> @ShrBox

建议开一个新的issue，我尝试了一下，单独出现中文和英文都不会有问题，只有当中文、英文和英文符号三者同时出现时客户端才会报错
