### ISSUE TITLE
[Bug]: dv.inputMode和dv.playMode一直是null

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#51]
### Describe the bug

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/a1398bef-497d-45b1-b0c8-8625be4ff22b)
![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/014e6c2a-e256-408f-8828-d50e936d27d0)

这个为什么一直返回的是null，任何情况下都是null，没有数字

### To Reproduce

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/30e06a1e-ed7f-4d34-98d4-8a4bf83d2cd2)

### Expected behavior

正常按照文档所述返回一个integer

### Platform

Win10

### BDS Version

1.20.62

### LeviLamina Version

0.9.0

### LegacyScriptEngine Version

0.4.1

**Comment by engsr6982** [comment]
> “这个为什么一直返回的是null，任何情况下都是null，没有数字”

因为被注释掉了哇。

https://github.com/LiteLDev/LegacyScriptEngine/blob/c617071b96d2fb80ec81629248973a79219a2b5e/src/legacy/api/DeviceAPI.cpp#L151-L171

**Comment by yufengya0420** [comment]
啊？是不能用吗？

**Comment by engsr6982** [comment]
> 啊？是不能用吗？

这个接口被注释了，所以是null
js访问object中不存在的属性/方法就是null哇

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/109733049/b1764c08-a44a-4c91-91fb-42cc86f4e1eb)

**Comment by ShrBox** [comment]
此API在LLSE就已经被注释了，大概是忘删文档了

**Comment by ShrBox** [comment]
Device::inputMode已被重新加入
