### ISSUE TITLE
[Bug]: onPlayerPullFishingHook事件回调函数无法正常执行

### ISSUE THREAD

**Issue by luoqing510** [LiteLDev/LegacyScriptEngine#55]
### Describe the bug

onPlayerPullFishingHook监听事件是成功的,但是回调函数无法被正常调用

### To Reproduce

```JavaScript
mc.listen("onPlayerPullFishingHook", (pl, en, it) => {
    logger.warn(pl.name)
})
```

### Expected behavior

可以正常调用回调函数

### Platform

windows11

### BDS Version

1.20.62

### LeviLamina Version

0.9.2

### LegacyScriptEngine Version

0.4.1

**Comment by ShrBox** [comment]
此事件还未被加入到LSE中，会在后续版本加入

**Comment by ShrBox** [comment]
Done c530e488b40291c7389af4a187abe182d3fe17f7
