### ISSUE TITLE
[Bug]: onMobTrySpawn事件失效

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#59]
### Describe the bug

onMobTrySpawn监听事件无法正常生效

### To Reproduce

//拦截幻翼、流浪商人生成
mc.listen("onMobTrySpawn", (typeName, _pos) => {
    if (typeName === "minecraft:phantom" || typeName === "minecraft:wandering_trader") {
        return false;
    }
})

### Expected behavior

正常拦截生物生成

### Platform

Win10

### BDS Version

1.20.62.02

### LeviLamina Version

0.9.2

### LegacyScriptEngine Version

0.4.3

**Comment by Tsubasa6848** [comment]
因为这两个玩意不走正常的生物生成逻辑，需要单独处理。
BDS的生物生成并不是全部统一的逻辑，本身就是很抽象的，现在只能拦截生物自然刷新。别的非正常逻辑的都不包含在内。
BDS本身这套逻辑就很抽象，想通过一个点位拦截全部生物生成也基本上不太可能。

**Comment by yufengya0420** [comment]
> 因为这两个玩意不走正常的生物生成逻辑，需要单独处理。 BDS的生物生成并不是全部统一的逻辑，本身就是很抽象的，现在只能拦截生物自然刷新。别的非正常逻辑的都不包含在内。 BDS本身这套逻辑就很抽象，想通过一个点位拦截全部生物生成也基本上不太可能。

但是在LL2可以正常拦截，LL3不行
