### ISSUE TITLE
[Feature]: Add a way to unsubscribe from event listeners

### ISSUE THREAD

**Issue by beanburrito9** [LiteLDev/LegacyScriptEngine#61]
### Is your feature request related to a problem? Please describe.

Sometimes you want to listen to an event momentarily and no longer use it when you're done with it. However, LeviLamina's API currently does not offer a way to unsubscribe from event listeners, so you're stuck with the event triggering forever.

### Describe the solution you'd like

A way to unsubscribe from event listeners. For example:
mc.listen(usual parameters): number that identifies the listener | null if event listener registration failed 
mc.unlisten(number that the event listener returned to cancel the event): boolean; false if event listener deregistration failed

**Comment by ShrBox** [comment]
Unfortunately, LegacyScriptEngine is a transitional solution before LeviScript done, so we will not add any new feature into it.
