### ISSUE TITLE
[Bug]: Native Api中使用hook会导致服务器崩溃（补上了崩溃日志）

### ISSUE THREAD

**Issue by heyhey123-git** [LiteLDev/LegacyScriptEngine#63]
### Describe the bug

使用native api里NativeFunction原生函数的hook方法后，当原函数被调用，服务端就会崩溃

### To Reproduce

如下例，当玩家与村民等实体交互时，即原函数被调用时，服务端崩溃
```javascript
let func = NativeFunction.fromSymbol("?interact@Player@@QEAA_NAEAVActor@@AEBVVec3@@@Z");
func.hook((pl, act, pos) => {
    let res = func.call(pl, act, pos);
    return res;
});
``` 

### Expected behavior

不崩溃

### Platform

win10

### BDS Version

1.20.62

### LeviLamina Version

0.9.2

### LegacyScriptEngine Version

0.4.3

### Additional context

[minidump_2024-03-10_11-08-04.dmp](https://github.com/LiteLDev/LegacyScriptEngine/files/14616870/minidump_2024-03-10_11-08-04.dmp)

[trace_2024-03-10_11-08-04.log](https://github.com/LiteLDev/LegacyScriptEngine/files/14616857/trace_2024-03-10_11-08-04.log)

**Comment by yufengya0420** [comment]
不仅与实体，与箱子交互（右键打开箱子）也会崩

**Comment by WuHuiZhang6902** [comment]
据我所知ll3下的LSE没有native api了吧😂
