### ISSUE TITLE
[Bug]: API-entity.setMovementSpeed无法为矿车(minecart)设置实体速度

### ISSUE THREAD

**Issue by superwfox** [LiteLDev/LegacyScriptEngine#65]
### Describe the bug

![IMG_2360](https://github.com/LiteLDev/LegacyScriptEngine/assets/65709399/3ed4a7f3-67e7-48d8-910d-377755d9f55f)
![IMG_2359](https://github.com/LiteLDev/LegacyScriptEngine/assets/65709399/cec4a1c9-e66c-4ad2-bf11-07ab0cbdb4f9)

### To Reproduce

使用onRide事件获取 rider和saddle
对rider可以正常使用sendText 
但对saddle.setMovementSpeed时会出错 提示空指针

### Expected behavior

API可以正确将实体的速度component设置为参数应有的值

**Comment by ShrBox** [comment]
因为矿车没有速度属性，我也找不到任何给矿车添加该属性的方法
