### ISSUE TITLE
[Bug]: onAttackEntity 事件无法获取到攻击所造成的伤害

### ISSUE THREAD

**Issue by TRDSCSH** [LiteLDev/LegacyScriptEngine#69]
### Describe the bug

`onAttackEntity` 事件无法获取攻击所造成的伤害。
对于其监听函数原型 `function(player,entity,damage)` ，其中 `damage` 的获取到的值总是 `undefined`

### To Reproduce

1. 在服务端装载以下 JS 插件
```JavaScript
mc.listen("onAttackEntity", (pl, en, da) => {
    log(`${pl} ${en} ${da}`);
});
```

2. 进入服务器攻击生物，会发现有类似以下的输出
```
21:22:52.926 INFO [TestPlugin] [object Object] [object Object] undefined
```
这段输出说明获取攻击所造成的伤害失败。

### Expected behavior

成功获取攻击所造成的伤害值

### Platform

Windows Server 2022 Datacenter

### BDS Version

1.20.62.02

### LeviLamina Version

0.9.3

### LegacyScriptEngine Version

0.4.10

**Comment by ShrBox** [comment]
在LL2，onAttackEntity所传的damage值本质上不是伤害值，而是伤害来源

**Comment by superwfox** [comment]
awa？
