### ISSUE TITLE
LLSE Python `asyncio`无法使用

### ISSUE THREAD

**Issue by lgc2333** [LiteLDev/LegacyScriptEngine#7]
### 异常模块

ScriptEngine (脚本引擎)

### 操作系统

Windows 11

### LiteLoader 版本

2.12.0

### BDS 版本

1.19.71.02

### 发生了什么?

![image](https://user-images.githubusercontent.com/59048777/227646413-0fb4c1ae-7152-41c7-b0c9-ca07fcf843a4.png)

**Comment by Mooling0602** [comment]
> > `asyncio` 有自己的事件循环啊…… 如果 `asyncio` 不能适配的话，我这里可以实现第三方实现的协程，就能适配 `LL` 了。
> 
> 是这样，asyncio依赖于py底层的调度算法。LLSE为了实现完善的多引擎隔离重写了这部分调度以及GIL相关的代码，因此与标准库部分设施相不兼容，这也没有办法，因为以py目前相关的机制并不能达到我们需要的目的。 等py3.12更新后，LL将转为使用3.12更新的isolated GIL API来彻底解决此问题。在此之前，欢迎社区自行实现协程来自行实现相关效果。

3.12已经出了吧，有消息吗，想把我的MCDR插件移植过来
