### ISSUE TITLE
[Bug]: 监听方块相关事件时出错

### ISSUE THREAD

**Issue by TRDSCSH** [LiteLDev/LegacyScriptEngine#79]
### Describe the bug

监听 `onBlockChanged` `onRedStoneUpdate` `onFireSpread` `onPistonTryPush` `onPistonPush` `onFarmLandDecay` 等事件时出错，这些事件都是方块相关事件。

具体报错内容：
```
19:37:40.381 ERROR [legacy-script-engine-quickjs] Event Callback Failed!
19:37:40.381 ERROR [legacy-script-engine-quickjs] Uncaught Exception Detected!
19:37:40.381 ERROR [legacy-script-engine-quickjs] In Event: onBlockChanged
```

### To Reproduce

服务端运行后，依次执行以下命令：
```
jsdebug const events = ['onBlockChanged', 'onRedStoneUpdate', 'onFireSpread', 'onPistonTryPush', 'onPistonPush', 'onFarmLandDecay'];
```
```
jsdebug for (let i in events) mc.listen(events[i], () => {});
```

然后进入服务器触发相关事件即可。

### Expected behavior

可以正常监听方块相关事件。

### Platform

Windows 11 专业版

### BDS Version

1.20.72.01

### LeviLamina Version

0.10.1

### LegacyScriptEngine Version

0.5.1

**Comment by ShrBox** [comment]
https://github.com/LiteLDev/LeviLamina/issues/1499
