### ISSUE TITLE
[Bug]: 使用 mc.getBlock() 时卡服

### ISSUE THREAD

**Issue by TRDSCSH** [LiteLDev/LegacyScriptEngine#80]
### Describe the bug

在服务端使用 `mc.getBlock()` 会导致卡服。

### To Reproduce

服务端启动完成后，运行以下命令：
```
jsdebug mc.getBlock(0, 0, 0, 0);
```

可以发现服务端没有对应的输出，阻塞了。

使用 `Ctrl + C` 可以正常终止服务端运行。

### Expected behavior

使用 `mc.getBlock()` 时正常获取方块而不阻塞服务端运行。

### Platform

Windows 11 专业版

### BDS Version

1.20.72.01

### LeviLamina Version

0.10.1

### LegacyScriptEngine Version

0.5.1

**Comment by ShrBox** [comment]
https://github.com/LiteLDev/LeviLamina/issues/1499
