### ISSUE TITLE
[Bug]: onMobTrySpawn事件出错

### ISSUE THREAD

**Issue by panjj95** [LiteLDev/LegacyScriptEngine#81]
### Describe the bug

![image](https://github.com/LiteLDev/LegacyScriptEngine/assets/113979796/0921ffc5-865f-491e-ae4b-baa592369d9f)

### To Reproduce

mc.listen("onMobTrySpawn", (typeName, _pos) => {
if (typeName === "minecraft:phantom" || typeName === "minecraft:wandering_trader") {
return false;
}
})

### Expected behavior

正常使用

### Platform

Windows 10 

### BDS Version

1.20.72.01

### LeviLamina Version

0.10.1

### LegacyScriptEngine Version

0.5.1

**Comment by ShrBox** [comment]
https://github.com/LiteLDev/LeviLamina/issues/1499
