### ISSUE TITLE
[Bug]: onMobTrySpawn Event Fail

### ISSUE THREAD

**Issue by Caldron47** [LiteLDev/LegacyScriptEngine#83]
### Describe the bug

Error everytime any mob spawns

### To Reproduce

Use this code:

```
mc.listen("onMobTrySpawn",function(typeName,pos) {
      log(typeName);
})
```

Wait for mobs to spawn

### Expected behavior

There is no error and the mob's typeName is logged on the console

### Screenshots

![onMobTrySpawnError](https://github.com/LiteLDev/LegacyScriptEngine/assets/99594434/2852ec54-ebbc-4dbb-aa0a-a262f99f8f76)

### Platform

Windows 10

### BDS Version

1.20.72

### LeviLamina Version

0.10.2

### LegacyScriptEngine Version

0.5.2

**Comment by ShrBox** [comment]
Are you sure you are using LSE 0.5.2?
I can't reproduce it on LSE 0.5.2.

**Comment by Caldron47** [comment]
> Are you sure you are using LSE 0.5.2? I can't reproduce it on LSE 0.5.2.

Sorry, the one that throws error is 0.5.1. I thought i installed the latest one yesterday. However, in 0.5.2, the event works but the typeName always has this additional "<>" so it makes the mob typeName to be like "minecraft:zombified_pigman<>" which is odd
