### ISSUE TITLE
[Bug]: 弹射物相关事件不会触发

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LegacyScriptEngine#87]
### Describe the bug

"onProjectileHitBlock" - 方块被弹射物击中
"onProjectileHitEntity" - 实体被弹射物击中

目前都不能正常触发

### To Reproduce

mc.listen("onProjectileHitBlock", (block, source)=>{log('命中方块触发事件')});

### Expected behavior

条件允许的情况下麻烦尽快恢复

### Platform

win 10

### BDS Version

1.20.71.01

### LeviLamina Version

LeviLamina-0.10.5+d9516c73d

### LegacyScriptEngine Version

v0.5.2

**Comment by ShrBox** [comment]
未实现
