### ISSUE TITLE
[Bug]: lse中设置插件依赖库无法正常返回结果

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LegacyScriptEngine#89]
### Describe the bug

ll.require(path[,remotePath])
返回内容为Null

### To Reproduce

log(ll.getAllPluginInfo())
log(ll.require("Intensify.js"))

### Expected behavior

搜索已加载插件列表。如果依赖库已经被加载，则直接返回成功。

### Screenshots

![{FE407DC7-DA4D-43a1-8B06-E1E556F7A55B}](https://github.com/LiteLDev/LegacyScriptEngine/assets/82281127/af8ff148-2cd5-499e-8f89-a8e0dda56ad4)
![{2815AA06-5E41-49ee-9143-E577A52965D3}](https://github.com/LiteLDev/LegacyScriptEngine/assets/82281127/fe4aecff-8f51-4235-aff5-20c2a76550ec)

### Platform

Windows 10

### BDS Version

1.20.71.01

### LeviLamina Version

LeviLamina-0.10.5+d9516c73d

### LegacyScriptEngine Version

v0.5.2

**Comment by ShrBox** [comment]
在LeviLamina中，正确设置依赖的方法是在`manifest.json`中注明
