### ISSUE TITLE
[Bug]: spawnSimulatedPlayer API创建假人导致崩服

### ISSUE THREAD

**Issue by yufengya0420** [LiteLDev/LegacyScriptEngine#90]
### Describe the bug

![D35A37F6C755EDAC5853C5BA89CA3A64](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/017762f4-64bb-4596-b77e-36661b9ffaa0)

崩服日志：
[crash.zip](https://github.com/LiteLDev/LegacyScriptEngine/files/14863840/crash.zip)

创建假人导致崩服，无论假人名字是否含有中文

### To Reproduce

使用spawnSimulatedPlayer API创建假人

### Expected behavior

创建假人不崩服，并且希望假人名字支持中文
在LL2中，创建假人使用的名字没有任何限制，包括中文、下划线和数字，希望在LL3中一样支持

### Screenshots

![D35A37F6C755EDAC5853C5BA89CA3A64](https://github.com/LiteLDev/LegacyScriptEngine/assets/99462074/dcc8101a-d0bc-41f8-bf1d-5db76c22599c)

### Platform

Win10

### BDS Version

1.20.72

### LeviLamina Version

0.10.5

### LegacyScriptEngine Version

0.5.2

**Comment by ShrBox** [comment]
![图片](https://github.com/LiteLDev/LegacyScriptEngine/assets/53301243/818a3955-b7f0-47eb-bb3d-44982a47d6ad)
无法复现
