### ISSUE TITLE
[Bug]: lse 对玩家造成伤害api不能正常工作

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LegacyScriptEngine#91]
### Describe the bug

player.hurt(Hurt);视乎从llse2.14.1到现在lse0.5.2一直无法正常工作，之前还能用获取实体对象来造成伤害，现在获取所有实体不会再获取到玩家的实体对象，至此只有直接修改玩家生命值和指令才能完成此项功能。

### To Reproduce

let allPlayer = mc.getOnlinePlayers();
    for (let i in allPlayer) {
        let player = allPlayer[i];
player.hurt(1)
}

### Expected behavior

能正常对玩家造成伤害

### Platform

Windows 10

### BDS Version

1.20.71.01

### LeviLamina Version

LeviLamina-0.10.5+d9516c73d

### LegacyScriptEngine Version

v0.5.2

**Comment by ShrBox** [comment]
你没指定第二个伤害类型的参数
