### ISSUE TITLE
[Bug]: nodejs 插件使用ll 加载相关命令报错

### ISSUE THREAD

**Issue by xianyubb** [LiteLDev/LegacyScriptEngine#93]
### Describe the bug

nodejs 插件使用ll reload 报错 
![E139B3E7AB721AF50D34A4F8C4AB4FC7](https://github.com/LiteLDev/LegacyScriptEngine/assets/111666543/e4fd2504-2f0c-4bbd-891a-3a4b6416970f)

包括ll unload 也是报错的
加载的文件是空的，有内容的试过了，一样的报错刷屏

### To Reproduce

![E139B3E7AB721AF50D34A4F8C4AB4FC7](https://github.com/LiteLDev/LegacyScriptEngine/assets/111666543/cc0d47fe-70e7-45ec-86f7-402841b17f3e)

### Expected behavior

我不记得ll2的nodejs能不能热重载了，但是希望ll3可以

### Platform

windows 11

### BDS Version

1.20,72

### LeviLamina Version

0.10,5

### LegacyScriptEngine Version

0.5.2

**Comment by ShrBox** [comment]
NodeJs引擎不支持热重载
