### ISSUE TITLE
[Bug]: 获取离线玩家 NBT 导致崩服

### ISSUE THREAD

**Issue by TRDSCSH** [LiteLDev/LegacyScriptEngine#94]
### Describe the bug

通过 [`mc.getPlayerNbt(uuid)`](https://lse.liteldev.com/zh/apis/GameAPI/Player/#nbt_2) 获取离线玩家 NBT 时崩服

### To Reproduce

在服务端执行以下命令即可：
```
jsdebug mc.getPlayerNbt(data.name2uuid('<playerName>'));
```
> 需要将命令中的 `<playerName>` 替换为离线玩家的玩家名。

### Expected behavior

正常获取离线玩家 NBT

### Platform

Windows 11 专业版

### BDS Version

1.20.72.01

### LeviLamina Version

0.10.5

### LegacyScriptEngine Version

0.5.3

**Comment by ShrBox** [comment]
uuid和xuid是两回事（

**Comment by TRDSCSH** [comment]
> uuid和xuid是两回事（

woc，我没注意到，可能打字手滑了（
等下我去服务器里面试一下uuid

**Comment by ShrBox** [comment]
已经在 31e170673daab88d396ac9e88929a5d8b53ea03d 中修复
