### ISSUE TITLE
[Bug]: lse中玩家改变盔甲栏事件无法正常触发

### ISSUE THREAD

**Issue by FBQingYi** [LiteLDev/LegacyScriptEngine#95]
### Describe the bug

"onSetArmor" - 玩家改变盔甲栏 不能正常监听

### To Reproduce

mc.listen("onSetArmor", (player, slotNum, item)=>{
    log('1')
});

### Expected behavior

能正常触发

### Platform

Windows 10

### BDS Version

1.20.71.01

### LeviLamina Version

LeviLamina-0.10.5+d9516c73d

### LegacyScriptEngine Version

v0.5.3

**Comment by ShrBox** [comment]
暂未实现
